### PR TITLE
Updated with composer

### PR DESCRIPTION
**Pull request by capitanfindusfi**
I've updated your project with composer as [Facebook PHP SDK](https://github.com/facebook/php-graph-sdk) suggests (trust me, it's way better). Will start working on frontend ASAP

### CODE REVIEW

**Comment by adhavalboy** [comment]
why did you delete the facebook library?

**Comment by adhavalboy** [comment]
I am getting HTTP ERROR 500

**Comment by adhavalboy** [comment]
Explain how it work ?

**Comment by capitanfindusfi** [comment]
@adhavalboy which error are you getting? And which version of PHP are you using?

**Comment by adhavalboy** [comment]
http://facebook.codersfield.com/login.php its version 5

**Pull request closed without merging**
